language: bash
sudo: required # Just in case testing `sudo` doesn't work for some reason.
addons:
  apt:
    packages: shellcheck
os:
 - linux
 - osx
dist: trusty # Shellcheck does not exist in precise.
script:
 - ./tests.sh
notifications:
  email: false
